import CryptoKit
import Foundation

/// Offline licence verification.
///
/// ## What this protects against
///
/// Licences are Ed25519 signatures over a small payload. The app embeds only
/// the **public** key, so producing a key that verifies requires the private
/// key, which never leaves the developer's machine. Forging a licence is
/// therefore as hard as breaking Ed25519 -- which is to say, not feasible.
/// Guessing, editing an existing key, or altering the name inside one all
/// fail the signature check.
///
/// ## What this does *not* protect against
///
/// No purely client-side scheme can be made airtight, and it is worth being
/// clear rather than implying otherwise:
///
/// - The binary is on the user's machine, so the verification branch can be
///   patched out by someone determined enough. Nothing here prevents that.
/// - A legitimate key can be shared, since validation is offline by design.
///
/// The mitigations below raise the effort required; they do not eliminate it.
/// Genuine enforcement needs server-side activation, which trades away
/// offline use. This is the same trade most indie Mac apps make.
@MainActor
final class LicenseManager: ObservableObject {
    static let shared = LicenseManager()

    /// Master switch for the paid tier. While this is false the app is
    /// freeware -- every feature is on, and the licence UI is hidden. The
    /// verification below is left fully intact so flipping this back to true
    /// re-arms the paywall without any of it having to be rewritten.
    static let paywallEnabled = false

    /// Generated by `Tools/licensekeygen.swift keypair`. Safe to ship: it can
    /// verify signatures but cannot create them.
    private static let publicKeyBase64 = "JYoCCvGKeHokgxAYy9suGyjgUiGBkjX/GCzDAmHJyu8="

    struct License: Equatable {
        var issued: Date
        /// `nil` for a lifetime licence.
        var expiryDays: Int?

        var isLifetime: Bool { expiryDays == nil }

        var expiry: Date? {
            expiryDays.map { issued.addingTimeInterval(TimeInterval($0) * 86_400) }
        }

        var isCurrentlyValid: Bool {
            guard let expiry else { return true }
            return Date() < expiry
        }
    }

    enum ActivationError: LocalizedError {
        case malformed
        case badSignature
        case expired

        var errorDescription: String? {
            switch self {
            case .malformed: return "That doesn't look like a Wavelength licence."
            case .badSignature: return "This licence isn't valid."
            case .expired: return "This licence has expired."
            }
        }
    }

    @Published private(set) var license: License?

    /// Deliberately recomputed from the stored key rather than cached as a
    /// flag, so there is no single boolean in memory to flip.
    var isPro: Bool {
        // Freeware: nothing is gated.
        guard Self.paywallEnabled else { return true }
        guard let stored = UserDefaults.standard.string(forKey: Self.storageKey) else { return false }
        guard let verified = Self.verify(stored) else { return false }
        return verified.isCurrentlyValid
    }

    private static let storageKey = "licenseKey"

    private init() {
        if let stored = UserDefaults.standard.string(forKey: Self.storageKey),
           let verified = Self.verify(stored), verified.isCurrentlyValid {
            license = verified
        }
    }

    @discardableResult
    func activate(_ input: String) -> Result<License, ActivationError> {
        let cleaned = Self.normalise(input)
        guard !cleaned.isEmpty else { return .failure(.malformed) }
        guard let verified = Self.verify(cleaned) else {
            // A malformed key and a well-formed forgery are reported the same
            // way; distinguishing them only helps someone probing the format.
            return .failure(.badSignature)
        }
        guard verified.isCurrentlyValid else { return .failure(.expired) }

        UserDefaults.standard.set(cleaned, forKey: Self.storageKey)
        license = verified
        return .success(verified)
    }

    func deactivate() {
        UserDefaults.standard.removeObject(forKey: Self.storageKey)
        license = nil
    }

    // MARK: - Verification

    private static func normalise(_ input: String) -> String {
        input
            .replacingOccurrences(of: "WVLN1", with: "")
            .filter { !$0.isWhitespace }
            .uppercased()
    }

    /// Returns the licence only when the signature checks out against the
    /// embedded public key.
    private static func verify(_ key: String) -> License? {
        let parts = key.split(separator: "~")
        guard parts.count == 2,
              let payload = base32Decode(String(parts[0])),
              let signature = base32Decode(String(parts[1])),
              let publicKeyData = Data(base64Encoded: publicKeyBase64),
              let publicKey = try? Curve25519.Signing.PublicKey(rawRepresentation: publicKeyData),
              publicKey.isValidSignature(signature, for: payload),
              let text = String(data: payload, encoding: .utf8)
        else { return nil }

        // Payload is issued | nonce | optional days.
        let fields = text.split(separator: "|", omittingEmptySubsequences: false)
        guard fields.count >= 2, let issuedStamp = TimeInterval(fields[0]) else { return nil }

        return License(
            issued: Date(timeIntervalSince1970: issuedStamp),
            expiryDays: fields.count > 2 ? Int(fields[2]) : nil
        )
    }

    private static let alphabet = Array("0123456789ABCDEFGHJKMNPQRSTVWXYZ")

    private static func base32Decode(_ text: String) -> Data? {
        var lookup: [Character: Int] = [:]
        for (index, character) in alphabet.enumerated() { lookup[character] = index }

        var bytes: [UInt8] = []
        var buffer = 0, bits = 0
        for character in text {
            guard let value = lookup[character] else { return nil }
            buffer = (buffer << 5) | value
            bits += 5
            if bits >= 8 {
                bytes.append(UInt8((buffer >> (bits - 8)) & 0xFF))
                bits -= 8
            }
        }
        return Data(bytes)
    }
}
